language: python
python:
  - "2.6"
  - "2.7"

install:
  - pip install . --no-deps
  - pip install --use-mirrors --no-deps -r example_djam_project/requirements.txt
script:
  - cd example_djam_project
  - ./manage.py test --verbosity=2 djam
